export {
  ElastiCacheManager,
  createElastiCacheManager,
  type ElastiCacheManagerConfig,
  type ElastiCacheOperationResult,
  type ReplicationGroupInfo,
  type NodeGroupInfo,
  type NodeMemberInfo,
  type CacheClusterInfo,
  type SnapshotInfo,
  type CreateReplicationGroupOptions,
  type ModifyReplicationGroupOptions,
  type ScaleReplicationGroupOptions,
  type CreateSnapshotOptions,
  type EventInfo,
  type EngineVersionInfo,
  type ParameterGroupInfo,
  type SubnetGroupInfo,
  type ListReplicationGroupsOptions,
  type ListSnapshotsOptions,
  type ListEventsOptions,
} from "./manager.js";
