/**
 * AWS CI/CD Pipeline Integration Module
 *
 * Exports CI/CD manager factory and types for CodePipeline, CodeBuild,
 * and CodeDeploy operations.
 */

export { createCICDManager } from './manager.js';

export type {
  // Common types
  CICDOperationResult,
  CICDManagerConfig,
  CICDManager,

  // Pipeline types
  PipelineStatus,
  StageStatus,
  ActionStatus,
  ActionCategory,
  SourceProvider,
  BuildProvider,
  DeployProvider,
  ArtifactStoreType,
  PipelineInfo,
  ArtifactStoreInfo,
  PipelineVariable,
  PipelineTrigger,
  StageInfo,
  StageBlocker,
  ActionInfo,
  PipelineSummary,
  PipelineExecutionSummary,
  SourceRevision,
  PipelineExecutionDetail,
  ArtifactRevision,
  ResolvedPipelineVariable,
  StageState,
  StageExecutionInfo,
  TransitionState,
  ActionState,
  ActionExecutionDetail,
  InputArtifact,
  OutputArtifact,

  // Build types
  BuildStatus,
  BuildPhaseType,
  BuildPhaseStatus,
  ComputeType,
  EnvironmentType,
  CodeBuildSourceType,
  ArtifactType,
  BuildProjectInfo,
  BuildSourceInfo,
  SecondarySourceVersion,
  BuildArtifactInfo,
  BuildCacheInfo,
  BuildEnvironmentInfo,
  EnvironmentVariable,
  WebhookInfo,
  WebhookFilterGroup,
  WebhookFilter,
  VpcConfigInfo,
  LogsConfigInfo,
  FileSystemLocation,
  BuildBatchConfig,
  BuildInfo,
  BuildPhase,
  BuildArtifactOutput,
  BuildLogs,
  BuildSummary,

  // Deploy types
  DeploymentStatus,
  DeploymentType,
  ComputePlatform,
  DeploymentOption,
  DeploymentReadyOption,
  GreenFleetProvisioningOption,
  InstanceAction,
  TrafficRoutingType,
  ApplicationInfo,
  DeploymentGroupInfo,
  TagFilter,
  AutoScalingGroupInfo,
  RevisionLocation,
  TriggerConfig,
  AlarmConfiguration,
  AutoRollbackConfiguration,
  DeploymentStyle,
  BlueGreenDeploymentConfiguration,
  LoadBalancerInfo,
  TargetGroupPairInfo,
  LastDeploymentInfo,
  EC2TagSet,
  OnPremisesTagSet,
  ECSServiceInfo,
  DeploymentInfo,
  DeploymentOverview,
  RollbackInfo,
  TargetInstances,
  DeploymentConfigInfo,
  TrafficRoutingConfig,

  // Options types
  ListPipelinesOptions,
  CreatePipelineOptions,
  UpdatePipelineOptions,
  ListPipelineExecutionsOptions,
  StartPipelineExecutionOptions,
  StopPipelineExecutionOptions,
  RetryStageExecutionOptions,
  ListActionExecutionsOptions,
  ListBuildProjectsOptions,
  CreateBuildProjectOptions,
  UpdateBuildProjectOptions,
  StartBuildOptions,
  ListBuildsOptions,
  ListBuildsForProjectOptions,
  ListApplicationsOptions,
  CreateApplicationOptions,
  ListDeploymentGroupsOptions,
  CreateDeploymentGroupOptions,
  UpdateDeploymentGroupOptions,
  CreateDeploymentOptions,
  ListDeploymentsOptions,
  ListDeploymentConfigsOptions,
  CreateDeploymentConfigOptions,
  BlueGreenDeploymentOptions,

  // Template types
  PipelineTemplate,
  TemplateStageInfo,
  TemplateParameter,
} from './types.js';

export { PIPELINE_TEMPLATES } from './types.js';
