export const browserCoreExamples = [
  "espada browser status",
  "espada browser start",
  "espada browser stop",
  "espada browser tabs",
  "espada browser open https://example.com",
  "espada browser focus abcd1234",
  "espada browser close abcd1234",
  "espada browser screenshot",
  "espada browser screenshot --full-page",
  "espada browser screenshot --ref 12",
  "espada browser snapshot",
  "espada browser snapshot --format aria --limit 200",
  "espada browser snapshot --efficient",
  "espada browser snapshot --labels",
];

export const browserActionExamples = [
  "espada browser navigate https://example.com",
  "espada browser resize 1280 720",
  "espada browser click 12 --double",
  'espada browser type 23 "hello" --submit',
  "espada browser press Enter",
  "espada browser hover 44",
  "espada browser drag 10 11",
  "espada browser select 9 OptionA OptionB",
  "espada browser upload /tmp/file.pdf",
  'espada browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "espada browser dialog --accept",
  'espada browser wait --text "Done"',
  "espada browser evaluate --fn '(el) => el.textContent' --ref 7",
  "espada browser console --level error",
  "espada browser pdf",
];
