export {
  AWSAIManager,
  createAWSAIManager,
  type AWSAIManagerConfig,
  type AIOperationResult,
  type NotebookInstanceInfo,
  type EndpointInfo,
  type ModelInfo,
  type TrainingJobInfo,
  type CreateNotebookOptions,
  type FoundationModelInfo,
  type InvokeModelOptions,
  type InvokeModelResult,
  type SentimentResult,
  type EntityResult,
  type KeyPhraseResult,
  type LanguageResult,
  type PiiEntityResult,
  type ImageSource,
  type ImageLabelResult,
  type FaceResult,
  type TextDetectionResult,
  type CelebrityResult,
  type ModerationLabelResult,
  type TranslationResult,
  type SupportedLanguage,
} from "./manager.js";
